### ISSUE TITLE
location info

### ISSUE THREAD

**Issue by pacomusume** [ricochhet/MHF-Quest-Resources#3]
[Monster_Hunter_Frontier_location_code（mapcode_fixed).xls](https://github.com/ricochhet/MHF-Quest-Resources/files/7011465/Monster_Hunter_Frontier_location_code.mapcode_fixed.xls)
I'd share the location area code here.Maybe some code is wrong,you can test it.Mapcode alright fixed.

**Comment by ricochhet** [comment]
Thanks for this! I won't be able to test until the weekend, but I took a quick look. 

I noticed some of the later MAP_CODE's don't match up with the dictionary. Your spreadsheet lists Historic Site as "86" for example. The dictionary lists it as "97." [LocationDictionary.cs Line 96](https://github.com/ricochhet/MHF-Quest-Resources/blob/fdd447d55afc222ee43ae519fe47fd64a5d62d7b/FrontierTools/Utils/LocationDictionary.cs#L96). 

I haven't tested all of the locations, so I don't know whether the dictionary or spreadsheet would be correct. Would you happen to know? Otherwise I'll work on testing this over the weekend.

**Comment by pacomusume** [comment]
You are right.My bad,I was worked on the location area code,forgot to used the map code.I'll correct it.

**Comment by pacomusume** [comment]
You can use cheat engine and Farcaster to test the location area code.Just backup your save data before you use cheat engine.
